[package]
name = "chain-reaction"
version = "1.0.1"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_vector_shapes = "0.6.0"
rand = "0.8.5"
webbrowser = "0.8.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

